import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Sidebar from './components/Sidebar/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gaplash | Anonimlikka asoslangan chatlashish dasturi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar/>
      </main>
    </div>
  )
}
